project:
  type: website

website:
  title: "How Can Data Science Contribute to Understanding the Khipu Code?"

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true
